### ISSUE TITLE
Exception on Docker installation

### ISSUE THREAD

**Issue by NinjaKittn** [redcode-labs/easyWSL#10]
Hi redcode team,

I tried to install a docker container and ran in to an exception. It looks like a hardcoded path to your projects folder.

`Unbehandelte Ausnahme: System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs. bei easyWSL.DistroInstaller.InstallDistro(String distroImage, String distroName, String distroPath, String easyWSLDataDirectory, String easyWSLDirectory, Boolean isCustomImageSpecified) in C:\Users\unrooted\Documents\projects\easyWSL\easyWSL\DistroInstaller.cs:Zeile 91. bei easyWSL.Program.Main(String[] args) in C:\Users\unrooted\Documents\projects\easyWSL\easyWSL\Program.cs:Zeile 147.PS`

**Comment by unrooted** [comment]
Hi, which exact docker container you've tried to use, and how did you run into this issue? The code itself doesn't have anything hard-coded when it comes to the path:
![image](https://user-images.githubusercontent.com/30440603/129870763-07f0febb-e891-428c-b9a8-0dbddaa1c188.png)
Since making the release package, I've changed my username on my machine and I never ran into the problem like your one.

**Comment by NinjaKittn** [comment]
Nginx for example. But it turns out that the I forgot to use the tag. It works if I use nginx:latest.

I found some hardcoded paths inside .suo file.

Thank you

**Comment by unrooted** [comment]
.suo is a file which contains local info about the project, it doesn't affect anything in easyWSL case

Great to hear that now it works if you use tag

**Comment by NinjaKittn** [comment]
Interesting. But this path must come from somewhere.
C:\Users\unrooted\Documents\projects\easyWSL\

Maybe it is only inside the release file.

**Comment by unrooted** [comment]
Check out the latest release [here](https://github.com/redcode-labs/easyWSL/releases/tag/1.2) - a few people tested it, and it works perfectly fine for us.
