### ISSUE TITLE
Problems with registering a new distribution

### ISSUE THREAD

**Issue by Raulm2x** [redcode-labs/easyWSL#33]
I was trying to install Arch Linux but I couldn't cause this error. I tried with another distributions but it always shows the same error. I'm new to easyWSL, so I don't know what maybe causes it. Thanks for your help.
![image](https://user-images.githubusercontent.com/73721158/228321207-589d2828-2a45-4b6f-995b-12c2739c9af6.png)

**Comment by RSCyberTech** [comment]
Same problem exactly, here.

**Comment by unrooted** [comment]
As bad as it may sound, but I'll go with a classic one: `Works on my machine`.
It seems like there might be an issue from time to time when tags on Docker Hub change. Due to the changes with some tags, we'll be forced to introduce some changes to supported distro list in the near future as some tags are no longer in existance. 

Please reach out to us if the issue still persists. 

![image](https://github.com/redcode-labs/easyWSL/assets/30440603/7e8d774e-e777-4edd-927a-7987c71f51e5)
